Simple_911/Models/Incident.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Simple_911.Models
{
    public class Incident
    {
        public int Id { get; set; }

        [Required]
        [Display(Name = "Address")]
        public string Address { get; set; }

        [Required]
        [Display(Name = "City")]
        public string? City { get; set; }

        [Required]
        [Display(Name = "State")]
        public string? State { get; set; }

        [Required]
        [Display(Name = "Zip")]
        public string? Zip { get; set; }

        [DataType(DataType.DateTime)]
        public DateTimeOffset Created { get; set; }

        [Display(Name = "Closed")]
        public bool IsClosed { get; set; }

        [DataType(DataType.PhoneNumber)]
        [Display(Name = "Callback Number")]
        public string? Callback { get; set; }

        [NotMapped]
        [Display(Name = "Callback Number")]
        public string FormattedPhone { get { return String.Format("{0:(###) ###-####}", Convert.ToInt64(Callback)); } }

        [NotMapped]
        public string? NumberStreet { get { return Address.Replace(" ", "+"); } }

        [NotMapped]
        [Display(Name = "Address Link")]
        public string AddressLink { get { return $"https://google.com/maps/search/{NumberStreet}+{City}+{State}+{Zip}"; } }

        [NotMapped]
        [Display(Name = "Formatted Time")]
        public string FormattedTime { get { return Created.ToString("MM/dd ~ H:mm"); } }

        [Display(Name = "Priority")]
        public int PriorityId { get; set; }

        [Display(Name = "Call Type")]
        public int CallTypeId { get; set; }

        [Display(Name = "Unit Status")]
        public int StatusId { get; set; }

        [Display(Name = "Call Taker")]
        public string CallTakerId { get; set; }

        [Display(Name = "Dispatcher")]
        public string? DispatcherId { get; set; }

        [Display(Name = "Primary Unit")]
        public string? PrimaryUnitId { get; set; }

        [Display(Name = "Patient Age")]
        public string? PtAge { get; set; }

        [Display(Name = "Patient Sex")]
        public string? PtSex { get; set; }

        [Display(Name = "Patient Conciousness")]
        public string? PtCon { get; set; }

        [Display(Name = "Patient Breathing")]
        public string? PtBreath { get; set; }

        [Display(Name = "Patient History")]
        public string? PtHistory { get; set; }


        public virtual Priority Priority { get; set; }

        public virtual CallType CallType { get; set; }

        public virtual Status Status { get; set; }

        public virtual SimpleUser CallTaker { get; set; }

        public virtual SimpleUser? Dispatcher { get; set; }

        public virtual SimpleUser? PrimaryUnit { get; set; }

        public virtual ICollection<IncidentNote> Notes { get; set; } = new HashSet<IncidentNote>();

        public virtual ICollection<IncidentSupport> Supports { get; set; } = new HashSet<IncidentSupport>();
    }
}

Simple_911/Models/TimeKeeper.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Simple_911.Models
{
    public class TimeKeeper
    {
        public int Id { get; set; }

        [DataType(DataType.DateTime)]
        public DateTimeOffset TCreated { get; set; }

        [DataType(DataType.DateTime)]
        public DateTimeOffset? TDispatched { get; set; }

        [DataType(DataType.DateTime)]
        public DateTimeOffset? TEnroute { get; set; }

        [DataType(DataType.DateTime)]
        public DateTimeOffset? TOnscene { get; set; }

        [DataType(DataType.DateTime)]
        public DateTimeOffset? TTransporting { get; set; }

        [DataType(DataType.DateTime)]
        public DateTimeOffset? THospital { get; set; }

        [DataType(DataType.DateTime)]
        public DateTimeOffset? TInService { get; set; }

        [DataType(DataType.DateTime)]
        public DateTimeOffset? TOOS { get; set; }

        [DataType(DataType.DateTime)]
        public DateTimeOffset? TAssist { get; set; }

        [NotMapped]
        public string Dispatched { get { return TDispatched.Value.ToString("MM/dd/yyyy ~ H:mm EST"); } }

        [Display(Name = "Incident")]
        public int IncidentId { get; set; }

    }
}

Simple_911/Controllers/IncidentsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Simple_911.Data;
using Simple_911.Models;
using Simple_911.Services.Interfaces;

namespace Simple_911.Controllers
{
    public class IncidentsController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<SimpleUser> _userManager;
        private readonly ITIncidentsService _incidentsService;

        public IncidentsController(ApplicationDbContext context, UserManager<SimpleUser> userManager, ITIncidentsService incidentsService)
        {
            _context = context;
            _userManager = userManager;
            _incidentsService = incidentsService;
        }

        #region GET: INCIDENTS
        [Authorize(Roles = "Admin, Manager")]
        public async Task<IActionResult> Index()
        {
            var applicationDbContext = _context.Incidents.Include(i => i.CallTaker).Include(i => i.Dispatcher).Include(i => i.PrimaryUnit).Include(i => i.Priority).Include(i => i.Status).Include(i => i.CallType);
            return View(await applicationDbContext.ToListAsync());
        }
        #endregion

        #region GET: DASHBOARD
        [Authorize(Roles = "Admin, Manager, Dispatcher, Call Taker, Ground Unit")]
        public async Task<IActionResult> Dashboard()
        {
            var applicationDbContext = _context.Incidents.Include(i => i.CallTaker).Include(i => i.Dispatcher).Include(i => i.PrimaryUnit).Include(i => i.Priority).Include(i => i.Status).Include(i => i.CallType);
            return View(await applicationDbContext.ToListAsync());
        }
        #endregion

        #region GET: DETAILS
        [Authorize(Roles = "Admin, Manager, Dispatcher, Call Taker, Ground Unit")]
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            Incident incident = await _incidentsService.GetIncidentByIdAsync(id.Value);

            if (incident.Supports.Count >= 1)
            {
                foreach (var s in incident.Supports)
                {
                    SimpleUser user = _context.Users.Find(s.SupportUnitId);

                    s.SupportUnit = user;

                    _context.SaveChangesAsync();
                }
            }

            if (incident == null)
            {
                return NotFound();
            }

            return View(incident);
        }
        #endregion

        #region GET: CREATE
        [Authorize(Roles = "Admin, Manager, Dispatcher, Call Taker")]
        public IActionResult Create()
        {
            ViewData["PriorityId"] = new SelectList(_context.Priorities, "Id", "Name");
            ViewData["CallTypeId"] = new SelectList(_context.CallTypes, "Id", "Name");
            return View();
        }
        #endregion

        #region POST: CREATE
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin, Manager, Dispatcher, Call Taker")]
        public async Task<IActionResult> Create([Bind("Id,Address,City,State,Zip,Created,IsClosed,Callback,PriorityId,CallTypeId,StatusId,CallTakerId,DispatcherId,PrimaryUnitId,PtAge,PtSex,PtCon,PtBreath,PtHistory")] Incident incident)
        {
            incident.DispatcherId = null;

            incident.PrimaryUnitId = null;

            incident.IsClosed = false;

            SimpleUser user = await _userManager.GetUserAsync(User);

            incident.CallTakerId = user.Id;

            incident.Created = DateTimeOffset.Now;

            incident.StatusId = 1; // "1" is "Pending"

            _context.Add(incident);

            await _context.SaveChangesAsync();

            return RedirectToAction(nameof(Dashboard));
        }
        #endregion

        #region GET: PATIENT
        [Authorize(Roles = "Admin, Manager, Dispatcher, Call Taker")]
        public async Task<IActionResult> Patient(int? id)
        {
            var ptSex = new List<string> {
        "",
        "MALE",
        "FEMALE",
      };
            var ptCon = new List<string> {
        "",
        "CONSCIOUS",
        "UNCONSCIOUS",
      };
            var ptBreath = new List<string> {
        "",
        "BREATHING",
        "NOT BREATHING",
      };

            ViewData["PtSex"] = new SelectList(ptSex);
            ViewData["PtCon"] = new SelectList(ptCon);
            ViewData["PtBreath"] = new SelectList(ptBreath);
            Incident incident = await _incidentsService.GetIncidentByIdAsync(id.Value);

            return View(incident);
        }
        #endregion

        #region POST: PATIENT
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin, Manager, Dispatcher, Call Taker")]
        public async Task<IActionResult> Patient(int? id, [Bind("Id,Address,City,State,Zip,Created,IsClosed,Callback,PriorityId,CallTypeId,StatusId,CallTakerId,DispatcherId,PrimaryUnitId,PtAge,PtSex,PtCon,PtBreath,PtHistory")] Incident incident)
        {
            _context.Update(incident);

            await _context.SaveChangesAsync();

            if (incident.PrimaryUnit != null)
            {
                return RedirectToAction("Details", new
                {
                    id = id
                });
            }
            else
            {
                return RedirectToAction(nameof(Dashboard));
            }
        }
        #endregion

        #region GET: EDIT
        [Authorize(Roles = "Admin, Manager, Dispatcher, Call Taker")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var incident = await _context.Incidents.FindAsync(id);
            if (incident == null)
            {
                return NotFound();
            }
            ViewData["CallTakerId"] = new SelectList(_context.Users, "Id", "FullName", incident.CallTakerId);
            ViewData["DispatcherId"] = new SelectList(_context.Users, "Id", "FullName", incident.DispatcherId);
            ViewData["PrimaryUnitId"] = new SelectList(_context.Users, "Id", "UnitNumber", incident.PrimaryUnitId);
            ViewData["PriorityId"] = new SelectList(_context.Priorities, "Id", "Name", incident.PriorityId);
            ViewData["StatusId"] = new SelectList(_context.Statuses, "Id", "Name", incident.StatusId);
            ViewData["CallTypeId"] = new SelectList(_context.CallTypes, "Id", "Name", incident.CallTypeId);
            return View(incident);
        }
        #endregion

        #region POST: EDIT
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin, Manager, Dispatcher, Call Taker")]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Address,City,State,Zip,Created,IsClosed,Callback,PriorityId,CallTypeId,StatusId,CallTakerId,DispatcherId,PrimaryUnitId,PtAge,PtSex,PtCon,PtBreath,PtHistory")] Incident incident)
        {
            if (id != incident.Id)
            {
                return NotFound();
            }

            try
            {
                _context.Update(incident);
                await _context.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!IncidentExists(incident.Id))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }
            return RedirectToAction(nameof(Dashboard));

            ViewData["CallTakerId"] = new SelectList(_context.Users, "Id", "FullName", incident.CallTakerId);
            ViewData["DispatcherId"] = new SelectList(_context.Users, "Id", "FullName", incident.DispatcherId);
            ViewData["PrimaryUnitId"] = new SelectList(_context.Users, "Id", "UnitNumber", incident.PrimaryUnitId);
            ViewData["PriorityId"] = new SelectList(_context.Priorities, "Id", "Name", incident.PriorityId);
            ViewData["StatusId"] = new SelectList(_context.Statuses, "Id", "Name", incident.StatusId);
            ViewData["CallTypeId"] = new SelectList(_context.CallTypes, "Id", "Name", incident.CallTypeId);
            return View(incident);
        }
        #endregion

        #region GET: EMD
        [Authorize(Roles = "Admin, Manager, Dispatcher, Call Taker")]
        public async Task<IActionResult> EMD(int id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var incident = await _incidentsService.GetIncidentByIdAsync(id);
            if (incident == null)
            {
                return NotFound();
            }
            ViewData["CallTakerId"] = new SelectList(_context.Users, "Id", "FullName", incident.CallTakerId);
            ViewData["DispatcherId"] = new SelectList(_context.Users, "Id", "FullName", incident.DispatcherId);
            ViewData["PrimaryUnitId"] = new SelectList(_context.Users, "Id", "UnitNumber", incident.PrimaryUnitId);
            ViewData["PriorityId"] = new SelectList(_context.Priorities, "Id", "Name", incident.PriorityId);
            ViewData["StatusId"] = new SelectList(_context.Statuses, "Id", "Name", incident.StatusId);
            ViewData["CallTypeId"] = new SelectList(_context.CallTypes, "Id", "Name", incident.CallTypeId);
            return View(incident);
        }
        #endregion

        #region GET: DISPATCH
        [Authorize(Roles = "Admin, Manager, Dispatcher")]
        public async Task<IActionResult> Dispatch(int id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var incident = await _incidentsService.GetIncidentByIdAsync(id);

Simple_911/Views/Incidents/Create.cshtml
@model Simple_911.Models.Incident

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Incident</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Address" class="control-label"></label>
                <input asp-for="Address" class="form-control" />
                <span asp-validation-for="Address" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="City" class="control-label"></label>
                <input asp-for="City" class="form-control" />
                <span asp-validation-for="City" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="State" class="control-label"></label>
                <input asp-for="State" class="form-control" />
                <span asp-validation-for="State" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Zip" class="control-label"></label>
                <input asp-for="Zip" class="form-control" />
                <span asp-validation-for="Zip" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Created" class="control-label"></label>
                <input asp-for="Created" class="form-control" />
                <span asp-validation-for="Created" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="IsClosed" /> @Html.DisplayNameFor(model => model.IsClosed)
                </label>
            </div>
            <div class="form-group">
                <label asp-for="Callback" class="control-label"></label>
                <input asp-for="Callback" class="form-control" />
                <span asp-validation-for="Callback" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PriorityId" class="control-label"></label>
                <select asp-for="PriorityId" class ="form-control" asp-items="ViewBag.PriorityId"></select>
            </div>
            <div class="form-group">
                <label asp-for="CallTypeId" class="control-label"></label>
                <select asp-for="CallTypeId" class ="form-control" asp-items="ViewBag.CallTypeId"></select>
            </div>
            <div class="form-group">
                <label asp-for="StatusId" class="control-label"></label>
                <select asp-for="StatusId" class ="form-control" asp-items="ViewBag.StatusId"></select>
            </div>
            <div class="form-group">
                <label asp-for="CallTakerId" class="control-label"></label>
                <select asp-for="CallTakerId" class ="form-control" asp-items="ViewBag.CallTakerId"></select>
            </div>
            <div class="form-group">
                <label asp-for="DispatcherId" class="control-label"></label>
                <select asp-for="DispatcherId" class ="form-control" asp-items="ViewBag.DispatcherId"></select>
            </div>
            <div class="form-group">
                <label asp-for="PtAge" class="control-label"></label>
                <input asp-for="PtAge" class="form-control" />
                <span asp-validation-for="PtAge" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PtSex" class="control-label"></label>
                <input asp-for="PtSex" class="form-control" />
                <span asp-validation-for="PtSex" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PtCon" class="control-label"></label>
                <input asp-for="PtCon" class="form-control" />
                <span asp-validation-for="PtCon" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PtBreath" class="control-label"></label>
                <input asp-for="PtBreath" class="form-control" />
                <span asp-validation-for="PtBreath" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PtHistory" class="control-label"></label>
                <input asp-for="PtHistory" class="form-control" />
                <span asp-validation-for="PtHistory" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Simple_911/Views/Incidents/Delete.cshtml
@model Simple_911.Models.Incident

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Incident</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Address)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Address)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.City)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.City)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.State)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.State)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Zip)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Zip)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Created)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Created)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.IsClosed)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.IsClosed)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Callback)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Callback)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PtAge)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PtAge)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PtSex)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PtSex)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PtCon)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PtCon)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PtBreath)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PtBreath)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PtHistory)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PtHistory)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Priority)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Priority.Id)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CallType)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CallType.Id)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Status)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Status.Id)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CallTaker)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CallTaker.Id)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Dispatcher)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Dispatcher.Id)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Simple_911/Views/Incidents/Dispatch.cshtml
@model Simple_911.Models.Incident
@using Microsoft.AspNetCore.Identity
@inject UserManager<SimpleUser> UserManager
@{
ViewData["Title"] = "Dispatch";
SimpleUser simpleUser = await UserManager.GetUserAsync(User);
}
<div>
   <div classxfont-weighteighteightgetainer-fluid">
      <div class="row gy-2">
         <div class="col-md-12 col">
            <div class="row col-cols-2 mt-5">
               <div style='text-align:right'>
                  <a asp-action="Dashboard"><button type="button" class="btn btn-primary">Back to List</button></a>     <a asp-action="Edit" asp-route-id="@Model?.Id"><button type="button" class="btn btn-primary">Edit</button></a>     <a href='@Model.AddressLink' method="get" target="_blank"><button type="button" class="btn btn-info">Map Location</button></a>     <a asp-action="" asp-route-id="@Model?.Id"><button type="button" class="btn btn-danger">Archive</button></a>
               </div>
               <div class="card col m-1 p-2 border-primary mb-3">
                  <div class="card-body">
                     @*Incident Type*@
                     <h3>@Model.CallType.Description</h3>
                     <hr />
                     @*Description of Ticket*@
                     <div class="row">
                        <div class="col-md-2">
                           <form asp-action="Dispatch">
                              <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                              <input type="hidden" asp-for="Id" />
                              <input type="hidden" asp-for="Callback" />
                              <input type="hidden" asp-for="CallTakerId" />
                              <input type="hidden" asp-for="Created" />
                              <input type="hidden" asp-for="Address" />
                              <input type="hidden" asp-for="City" />
                              <input type="hidden" asp-for="State" />
                              <input type="hidden" asp-for="Zip" />
                              <input type="hidden" asp-for="PriorityId" />
                              <input type="hidden" asp-for="CallTypeId" />
                              <input type="hidden" asp-for="Created" />
                              <input type="hidden" asp-for="PtSex" />
                              <input type="hidden" asp-for="PtAge" />
                              <input type="hidden" asp-for="PtBreath" />
                              <input type="hidden" asp-for="PtCon" />
                              <input type="hidden" asp-for="PtHistory" />
                              <div class="form-group">
                                 <label class="control-label">Primary Unit:</label>
                                 <select asp-for="PrimaryUnitId" class="form-control" asp-items="ViewBag.PrimaryUnitId"></select>
                                 <span asp-validation-for="PrimaryUnitId" class="text-danger"></span>
                                 <p></p>
                              </div>
                              <div class="form-group">
                                 <button class="btn btn-warning text-black"><b>Submit</b></button>
                                 <p></p>
                              </div>
                           </form>
                        <div>
                           <form asp-action="AddSupportUnit" asp-controller="Incidents" method="post">
                              <input type="hidden" asp-for="Id" name="IncidentId" />
                              <div class="form-group">
                                 <label class="control-label">Attach a Unit:</label>
                                 <select asp-for="@(new IncidentSupport().SupportUnitId)" class="form-control" asp-items="ViewBag.ABC"></select>   
                                 <p></p>
                              </div>
                              <div class="form-group">
                                 <button class="btn btn-warning text-black"><b>Submit</b></button>
                                 <p></p>
                              </div>
                           </form>
                        </div>
                        </div>
                  <div class="card col m-1 p-2 border-primary mb-3 style="max-width: 100rem;">
                     <div class="card-body">
                        <ul class="list-unstyled">
                           @*Type*@
                           <li>
                              <h6><strong>Call Type:</strong> <span class="">  @Model.CallType.Name</span></h6>
                           </li>
                           @*Priority*@
                           <li>
                              <h6><strong>Priority:</strong> <span class="">  @Model.Priority.Name</span></h6>
                           </li>
                           @*Date Time*@
                           <li>
                              <h6><strong>Date Created:</strong> <span class="">  @Model.Created.ToString("MMM dd - H:mm")</</span></h6>
                           </li>
                           @*Callback Number*@
                           <li>
                              <h6><strong>Callback Number:</strong> <span class="">  @Model.FormattedPhone</span></h6>
                           </li>
                           @*Call Taker*@
                           <li>
                              <h6><strong>Call Taker:</strong> <span class="">  @Model.CallTaker.FullName</span></h6>
                           </li>
                           @*Dispatcher*@
                           <li>
                              <h6><strong>Dispatcher:</strong> <span class="">  @simpleUser.FullName</span></h6>
                           </li>
                           @*Address*@
                           <li>
                              <h6><strong>Address:</strong> <span class="">  @Model.Address, @Model.City</span></h6>
                           </li>
                          @*Attached Units*@
                            <li>
                                <p>
                                    <b>Attached Units:</b> @foreach(IncidentSupport support in Model.Supports)
                                    {
                                        @($"{support.SupportUnit.UnitNumber} - ")
                                    } 
                                </p>
                            </li>
                        </ul>
                     </div>
                  </div>
               </div>
            </div>
         </div>
      </div>
   </div>
</div>
</div>
</div>
@section Scripts {
@{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Simple_911/Views/Incidents/Enroute.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}